# Schema for headless_clean filter settings
filter_settings.filter_headless_sanitize:
  type: mapping
  label: 'Headless HTML Sanitizer'
  mapping:
    allowed_tags:
      type: string
      label: 'Allowed HTML tags'
    allowed_attributes:
      type: string
      label: 'Allowed attributes'
    strict_mode:
      type: boolean
      label: 'Strict mode'
    log_sanitization:
      type: boolean
      label: 'Log sanitization actions'

# Schema definitions for CKEditor 5 plugins used in headless_clean format
# This prevents config validation warnings and allows proper AI constraints

editor.settings.plugins.ai_ckeditor:
  type: mapping
  label: 'AI CKEditor plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI assistant'
    allowed_blocks:
      type: sequence
      label: 'Allowed block types for AI generation'
      sequence:
        type: string
        label: 'Block type'
    disable_images:
      type: boolean
      label: 'Disable AI image generation'
    disable_tables:
      type: boolean
      label: 'Disable AI table generation'
    disable_code:
      type: boolean
      label: 'Disable AI code generation'

editor.settings.plugins.ckeditor5_link:
  type: mapping
  label: 'CKEditor 5 link plugin settings'
  mapping:
    enabled_decorators:
      type: sequence
      label: 'Link decorators'
      sequence:
        type: mapping
        label: 'Link decorator'
        mapping:
          label:
            type: string
            label: 'Decorator label'
          description:
            type: string
            label: 'Decorator description'
          attributes:
            type: mapping
            label: 'Link attributes'
            mapping:
              rel:
                type: string
                label: 'Rel attribute'
              target:
                type: string
                label: 'Target attribute'
          automatic:
            type: boolean
            label: 'Apply automatically'

editor.settings.plugins.ckeditor5_codeBlock:
  type: mapping
  label: 'CKEditor 5 code block plugin settings'
  mapping:
    languages:
      type: sequence
      label: 'Available programming languages'
      sequence:
        type: mapping
        label: 'Language definition'
        mapping:
          language:
            type: string
            label: 'Language identifier'
          label:
            type: string
            label: 'Language display label'

editor.settings.plugins.ckeditor5_heading:
  type: mapping
  label: 'CKEditor 5 heading plugin settings'
  mapping:
    enabled_headings:
      type: sequence
      label: 'Enabled heading levels'
      sequence:
        type: string
        label: 'Heading level'

# AI CKEditor plugin schemas - now handled flexibly in main schema

# Note: Individual AI plugin schemas removed in favor of flexible main schema

# AI CKEditor main plugin schema
editor.settings.plugins.ai_ckeditor_ai:
  type: mapping
  label: 'AI CKEditor main plugin settings'
  mapping:
    dialog:
      type: mapping
      label: 'Dialog settings'
      mapping:
        autoresize:
          type: string
          label: 'Auto resize'
        height:
          type: string
          label: 'Dialog height'
        width:
          type: string
          label: 'Dialog width'
        dialog_class:
          type: string
          label: 'Dialog CSS class'
    plugins:
      type: mapping
      label: 'AI sub-plugins'
      mapping:
        ai_ckeditor_help:
          type: mapping
          label: 'AI Help plugin settings'
        ai_ckeditor_audio:
          type: mapping
          label: 'AI Audio plugin settings'
        ai_ckeditor_content:
          type: mapping
          label: 'AI Content plugin settings'
        ai_ckeditor_images:
          type: mapping
          label: 'AI Images plugin settings'
        ai_ckeditor_translate:
          type: mapping
          label: 'AI Translate plugin settings'
        ai_ckeditor_tone:
          type: mapping
          label: 'AI Tone plugin settings'

# CKEditor 5 core plugin schemas for headless_plain_ai format
editor.settings.plugins.ckeditor5_bold:
  type: mapping
  label: 'CKEditor 5 Bold plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable bold formatting'

editor.settings.plugins.ckeditor5_italic:
  type: mapping
  label: 'CKEditor 5 Italic plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable italic formatting'

editor.settings.plugins.ckeditor5_essentials:
  type: mapping
  label: 'CKEditor 5 Essentials plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable essential features'

# Additional CKEditor 5 plugin schemas
editor.settings.plugins.ckeditor5_list:
  type: mapping
  label: 'CKEditor 5 List plugin settings'
  mapping:
    properties:
      type: mapping
      label: 'List properties'
      mapping:
        reversed:
          type: boolean
          label: 'Enable reversed lists'
        startIndex:
          type: boolean
          label: 'Enable start index'
    multiBlock:
      type: boolean
      label: 'Enable multi-block lists'

editor.settings.plugins.ckeditor5_plugin_pack_paste_markdown__paste_markdown:
  type: mapping
  label: 'CKEditor 5 Paste Markdown plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable paste markdown'

editor.settings.plugins.ckeditor5_plugin_pack_word_count__word_count:
  type: mapping
  label: 'CKEditor 5 Word Count plugin settings'
  mapping:
    word_count_enabled:
      type: boolean
      label: 'Enable word count'
    word_count_mode:
      type: string
      label: 'Word count mode'

# CKEditor 5 Media plugin schema
editor.settings.plugins.ckeditor5_media_media:
  type: mapping
  label: 'CKEditor 5 Media plugin settings'
  mapping:
    allow_view_mode_override:
      type: boolean
      label: 'Allow view mode override'

# CKEditor 5 Image Resize plugin schema
editor.settings.plugins.ckeditor5_imageResize:
  type: mapping
  label: 'CKEditor 5 Image Resize plugin settings'
  mapping:
    allow_resize:
      type: boolean
      label: 'Allow image resizing'

# CKEditor 5 Source Editing plugin schema
editor.settings.plugins.ckeditor5_sourceEditing:
  type: mapping
  label: 'CKEditor 5 Source Editing plugin settings'
  mapping:
    allowed_tags:
      type: sequence
      label: 'Allowed HTML tags'
      sequence:
        type: string
        label: 'HTML tag'
