# Schema for headless_clean filter settings
filter_settings.filter_headless_sanitize:
  type: mapping
  label: 'Headless HTML Sanitizer'
  mapping:
    allowed_tags:
      type: string
      label: 'Allowed HTML tags'
    allowed_attributes:
      type: string
      label: 'Allowed attributes'
    strict_mode:
      type: boolean
      label: 'Strict mode'
    log_sanitization:
      type: boolean
      label: 'Log sanitization actions'

# Schema definitions for CKEditor 5 plugins used in headless_clean format
# This prevents config validation warnings and allows proper AI constraints

editor.settings.plugins.ai_ckeditor:
  type: mapping
  label: 'AI CKEditor plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI assistant'
    allowed_blocks:
      type: sequence
      label: 'Allowed block types for AI generation'
      sequence:
        type: string
        label: 'Block type'
    disable_images:
      type: boolean
      label: 'Disable AI image generation'
    disable_tables:
      type: boolean
      label: 'Disable AI table generation'
    disable_code:
      type: boolean
      label: 'Disable AI code generation'

editor.settings.plugins.ckeditor5_link:
  type: mapping
  label: 'CKEditor 5 link plugin settings'
  mapping:
    enabled_decorators:
      type: sequence
      label: 'Link decorators'
      sequence:
        type: mapping
        label: 'Link decorator'
        mapping:
          label:
            type: string
            label: 'Decorator label'
          description:
            type: string
            label: 'Decorator description'
          attributes:
            type: mapping
            label: 'Link attributes'
            mapping:
              rel:
                type: string
                label: 'Rel attribute'
              target:
                type: string
                label: 'Target attribute'
          automatic:
            type: boolean
            label: 'Apply automatically'

editor.settings.plugins.ckeditor5_codeBlock:
  type: mapping
  label: 'CKEditor 5 code block plugin settings'
  mapping:
    languages:
      type: sequence
      label: 'Available programming languages'
      sequence:
        type: mapping
        label: 'Language definition'
        mapping:
          language:
            type: string
            label: 'Language identifier'
          label:
            type: string
            label: 'Language display label'

editor.settings.plugins.ckeditor5_heading:
  type: mapping
  label: 'CKEditor 5 heading plugin settings'
  mapping:
    enabled_headings:
      type: sequence
      label: 'Enabled heading levels'
      sequence:
        type: string
        label: 'Heading level'

# AI CKEditor plugin schemas - based on actual configuration structure
editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_help:
  type: mapping
  label: 'AI CKEditor Help plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Help'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_tone:
  type: mapping
  label: 'AI CKEditor Tone plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Tone'
    autocreate:
      type: boolean
      label: 'Auto create'
    provider:
      type: string
      label: 'AI Provider'
    tone_vocabulary:
      type: string
      label: 'Tone vocabulary'
    use_description:
      type: integer
      label: 'Use description'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_translate:
  type: mapping
  label: 'AI CKEditor Translate plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Translate'
    autocreate:
      type: boolean
      label: 'Auto create'
    provider:
      type: string
      label: 'AI Provider'
    translate_vocabulary:
      type: string
      label: 'Translate vocabulary'
    use_description:
      type: boolean
      label: 'Use description'
    language_source:
      type: string
      label: 'Language source'

# Additional AI plugin schemas for completeness
editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_completion:
  type: mapping
  label: 'AI CKEditor Completion plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Completion'
    provider:
      type: string
      label: 'AI Provider'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_modify_prompt:
  type: mapping
  label: 'AI CKEditor Modify Prompt plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Modify Prompt'
    provider:
      type: string
      label: 'AI Provider'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_reformat_html:
  type: mapping
  label: 'AI CKEditor Reformat HTML plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Reformat HTML'
    provider:
      type: string
      label: 'AI Provider'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_spellfix:
  type: mapping
  label: 'AI CKEditor Spellfix plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Spellfix'
    provider:
      type: string
      label: 'AI Provider'

editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_summarize:
  type: mapping
  label: 'AI CKEditor Summarize plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable AI Summarize'
    provider:
      type: string
      label: 'AI Provider'

# AI CKEditor main plugin schema
editor.settings.plugins.ai_ckeditor_ai:
  type: mapping
  label: 'AI CKEditor main plugin settings'
  mapping:
    dialog:
      type: mapping
      label: 'Dialog settings'
      mapping:
        autoresize:
          type: string
          label: 'Auto resize'
        height:
          type: string
          label: 'Dialog height'
        width:
          type: string
          label: 'Dialog width'
        dialog_class:
          type: string
          label: 'Dialog CSS class'
    plugins:
      type: mapping
      label: 'AI sub-plugins'
      mapping:
        ai_ckeditor_completion:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_completion
        ai_ckeditor_help:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_help
        ai_ckeditor_modify_prompt:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_modify_prompt
        ai_ckeditor_reformat_html:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_reformat_html
        ai_ckeditor_spellfix:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_spellfix
        ai_ckeditor_summarize:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_summarize
        ai_ckeditor_tone:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_tone
        ai_ckeditor_translate:
          type: editor.settings.plugins.ai_ckeditor_ai.plugins.ai_ckeditor_translate

# CKEditor 5 core plugin schemas for headless_plain_ai format
editor.settings.plugins.ckeditor5_bold:
  type: mapping
  label: 'CKEditor 5 Bold plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable bold formatting'

editor.settings.plugins.ckeditor5_italic:
  type: mapping
  label: 'CKEditor 5 Italic plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable italic formatting'

editor.settings.plugins.ckeditor5_essentials:
  type: mapping
  label: 'CKEditor 5 Essentials plugin settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable essential features'
