<?php

declare(strict_types=1);

namespace Drupal\graphql_compose_codegen\Service;

use Drupal\Core\Config\ConfigFactoryInterface;

/**
 * Generates TypeScript/GraphQL scaffolding from the Drupal content model.
 *
 * Produces three artefacts:
 *   1. Type definitions  — TypeScript interface additions for types/index.d.ts.
 *   2. GQL fragments     — inline fragment additions for node-by-path.ts.
 *   3. Renderer cases    — NodeRenderer switch-case stubs.
 *   4. Component stubs   — bare React component files per bundle.
 *
 * All output is scaffolding — intended to be reviewed and merged by a
 * developer, not auto-applied. The generator never modifies existing source
 * files directly.
 */
class TypeScriptGenerator {

  /**
   * Banner prepended to every generated file.
   */
  const FILE_BANNER = <<<'BANNER'
// ─────────────────────────────────────────────────────────────────────────────
// @generated by graphql_compose_codegen
// Command: drush gqcc:generate
//
// This file is a SCAFFOLD. Review it, then merge the pieces you need into
// your Next.js source files. Do NOT import or commit this file as-is.
// ─────────────────────────────────────────────────────────────────────────────
BANNER;

  public function __construct(
    private readonly SchemaInspector $inspector,
    private readonly ConfigFactoryInterface $configFactory,
  ) {}

  // ---------------------------------------------------------------------------
  // Public generators
  // ---------------------------------------------------------------------------

  /**
   * Generates TypeScript type definition additions.
   *
   * Produces one `export type Drupal<Bundle>` intersection type per bundle,
   * then a comment showing how to extend the DrupalNode union.
   *
   * @param array $bundles
   *   If non-empty, only generate for these bundle IDs.
   * @param array $skipFields
   *   Additional field names to skip.
   *
   * @return string
   *   Content for types.generated.d.ts.
   */
  public function generateTypeDefinitions(array $bundles = [], array $skipFields = []): string {
    $config   = $this->configFactory->get('graphql_compose_codegen.settings');
    $baseType = (string) ($config->get('base_ts_type') ?? 'NodeCommonFields');

    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into types/index.d.ts ──────────────────────────────';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);

    foreach ($bundleInfo as $bundle => $info) {
      $tsType  = $this->inspector->getTsTypeName($bundle);
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $fields  = $this->inspector->getFieldsForBundle($bundle, $skipFields);
      $label   = (string) ($info['label'] ?? $bundle);

      $lines[] = "// {$label}";
      $lines[] = "export type {$tsType} = {$baseType} & {";
      $lines[] = "  __typename: \"{$gqlType}\"";

      foreach ($fields as $field) {
        $opt      = $field['required'] ? '' : '?';
        $nullable = $field['required'] ? '' : ' | null';
        $comment  = "  // Drupal: {$field['name']} ({$field['drupal_type']})";
        $lines[]  = $comment;
        $lines[]  = "  {$field['gql_name']}{$opt}: {$field['ts_type']}{$nullable}";
      }

      $lines[] = '}';
      $lines[] = '';
    }

    // Union type reminder.
    $unionMembers = array_map(
      fn(string $b) => $this->inspector->getTsTypeName($b),
      array_keys($bundleInfo)
    );
    $lines[] = '// ── Extend DrupalNode union ─────────────────────────────────────────────────';
    $lines[] = '//';
    $lines[] = '// export type DrupalNode =';
    foreach ($unionMembers as $member) {
      $lines[] = "//   | {$member}";
    }
    $lines[] = '//   | ... (existing union members)';

    return implode("\n", $lines);
  }

  /**
   * Generates GraphQL inline fragment additions.
   *
   * Produces one `... on NodeFoo { }` block per bundle for inclusion inside
   * the NODE_BY_PATH_QUERY template literal in lib/queries/node-by-path.ts.
   *
   * @param array $bundles
   *   If non-empty, only generate for these bundle IDs.
   * @param array $skipFields
   *   Additional field names to skip.
   *
   * @return string
   *   Content for fragments.generated.ts.
   */
  public function generateFragments(array $bundles = [], array $skipFields = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Merge the following into lib/queries/node-by-path.ts ─────────────────────';
    $lines[] = '// Inside the NODE_BY_PATH_QUERY template literal, add each block to the';
    $lines[] = '// NodeUnion spread (after the existing `... on NodePlatform { ... }` blocks).';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);

    foreach ($bundleInfo as $bundle => $info) {
      $gqlType = $this->inspector->getGraphQlTypeName($bundle);
      $label   = (string) ($info['label'] ?? $bundle);
      $fields  = $this->inspector->getFieldsForBundle($bundle, $skipFields);

      $lines[] = "// {$label}";
      $lines[] = "... on {$gqlType} {";
      $lines[] = '  ${COMMON_NODE_FIELDS}';

      foreach ($fields as $field) {
        $selector = $this->getGqlSelector($field);
        $lines[]  = "  {$selector}";
      }

      $lines[] = '}';
      $lines[] = '';
    }

    return implode("\n", $lines);
  }

  /**
   * Generates NodeRenderer switch-case stubs.
   *
   * @param array $bundles
   *   If non-empty, only generate for these bundle IDs.
   *
   * @return string
   *   Content for node-renderer-cases.generated.tsx.
   */
  public function generateRendererCases(array $bundles = []): string {
    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Add these cases to components/drupal/NodeRenderer.tsx ────────────────────';
    $lines[] = '// 1. Import each new component at the top of NodeRenderer.tsx.';
    $lines[] = '// 2. Add the import { ... } lines below.';
    $lines[] = '// 3. Add each case inside the switch(node.__typename) block.';
    $lines[] = '';

    $bundleInfo = $this->inspector->getBundles($bundles);

    $imports = [];
    $cases   = [];

    foreach ($bundleInfo as $bundle => $info) {
      $tsType    = $this->inspector->getTsTypeName($bundle);
      $gqlType   = $this->inspector->getGraphQlTypeName($bundle);
      $component = str_replace('Drupal', '', $tsType);
      $label     = (string) ($info['label'] ?? $bundle);

      $imports[] = "import { {$component} } from \"@/components/drupal/{$component}\"";
      $cases[]   = "      // {$label}";
      $cases[]   = "      case \"{$gqlType}\":";
      $cases[]   = "        return <{$component} node={node as {$tsType}} />";
      $cases[]   = '';
    }

    $lines[] = '// Imports:';
    foreach ($imports as $i) {
      $lines[] = "// {$i}";
    }
    $lines[] = '';
    $lines[] = '// Cases (inside switch(node.__typename)):';
    foreach ($cases as $c) {
      $lines[] = "// {$c}";
    }

    return implode("\n", $lines);
  }

  /**
   * Generates a stub React component file for a single bundle.
   *
   * @param string $bundle
   *   Node bundle machine name.
   *
   * @return string
   *   Content for {ComponentName}.generated.tsx.
   */
  public function generateComponentStub(string $bundle): string {
    $tsType    = $this->inspector->getTsTypeName($bundle);
    $gqlType   = $this->inspector->getGraphQlTypeName($bundle);
    $component = str_replace('Drupal', '', $tsType);
    $label     = str_replace('_', ' ', ucwords($bundle, '_'));
    $fields    = $this->inspector->getFieldsForBundle($bundle);

    $lines = [self::FILE_BANNER, ''];
    $lines[] = '// ── Rename to ' . $component . '.tsx and move to components/drupal/ ─────────────';
    $lines[] = "import type { {$tsType} } from \"@/types\"";
    $lines[] = '';
    $lines[] = "/**";
    $lines[] = " * {$label} node component.";
    $lines[] = " *";
    $lines[] = " * GraphQL type: {$gqlType}";
    $lines[] = " * Replace this stub with your actual layout.";
    $lines[] = " */";
    $lines[] = "export function {$component}({ node }: { node: {$tsType} }) {";
    $lines[] = "  return (";
    $lines[] = "    <article>";
    $lines[] = "      <h1>{node.title}</h1>";
    $lines[] = '';
    $lines[] = "      {/* TODO: render {$label} — available fields: */}";

    foreach ($fields as $field) {
      $lines[] = "      {/* {$field['gql_name']}: {$field['ts_type']} */}";
    }

    if (empty($fields)) {
      $lines[] = "      {/* (no extra fields beyond NodeCommonFields) */}";
    }

    $lines[] = "    </article>";
    $lines[] = "  )";
    $lines[] = "}";

    return implode("\n", $lines);
  }

  // ---------------------------------------------------------------------------
  // Internal helpers
  // ---------------------------------------------------------------------------

  /**
   * Returns the GraphQL sub-selection for a field based on its TypeScript type.
   *
   * graphql_compose uses sub-selections for complex types. Scalar fields
   * (string, boolean, number) use bare field names.
   */
  protected function getGqlSelector(array $field): string {
    $name     = $field['gql_name'];
    $tsType   = $field['ts_type'];
    // Strip array suffix for type matching.
    $baseType = rtrim($tsType, '[]');

    return match (true) {
      $baseType === 'ProcessedText'   => "{$name} { processed }",
      $baseType === 'Link'            => "{$name} { url title }",
      $baseType === 'Image'           => "{$name} { url alt width height }",
      $baseType === 'DrupalMedia'     => "{$name} { __typename ... on MediaImage { mediaImage { url alt width height } } }",
      $baseType === 'TaxonomyTermRef' => "{$name} { name }",
      $baseType === 'RelatedNode'     => "{$name} { __typename title path }",
      $baseType === 'Author'          => "{$name} { name }",
      $baseType === 'DrupalParagraph' => "{$name} { \${PARAGRAPH_FRAGMENTS} }",
      $baseType === 'SmartDate'       => "{$name} { value { time } endValue { time } duration timezone }",
      $baseType === 'string'          => $name,
      $baseType === 'boolean'         => $name,
      $baseType === 'number'          => $name,
      default                         => "{$name} # TODO: add sub-selection for type {$baseType}",
    };
  }

}
