# Configuration schema for headless_clean module filters
filter_settings.filter_headless_sanitize:
  type: mapping
  label: 'Headless HTML Sanitizer settings'
  mapping:
    allowed_tags:
      type: string
      label: 'Allowed HTML tags'
      translatable: false
    allowed_attributes:
      type: string
      label: 'Allowed attributes'
      translatable: false
    strict_mode:
      type: boolean
      label: 'Strict mode'
    log_sanitization:
      type: boolean
      label: 'Log sanitization actions'
